### ISSUE TITLE
It works!

### ISSUE THREAD

**Issue by tnhh** [barneyboo/Mixary#1]
Got it working on Ubuntu but:

1. requirements.txt is missing
2. I didn't realise that you have to remove the comments from the config file
3. you should check the return value of r in get_auth (if you don't remove the comments from config then you will end up with a 400 error)
4. you should check that pbcopy exists before trying to run it

**Comment by barneyboo** [comment]
Fixed in dfa75a25487a036e21649ff5900d57749801dbe2, 7b2716fdadb26873e60932c3603fbd1d1310c518, a1b6964207825973198afa093fe566bc73683c99
